services:
  - type: web
    name: campusdeal-backend
    env: python
    plan: free
    region: frankfurt
    branch: main
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: daphne -b 0.0.0.0 -p $PORT campusdeal.asgi:application
    healthCheckPath: /health/
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: FRONTEND_URL
        value: "https://campusdeal.vercel.app"
      - key: CORS_ALLOWED_ORIGINS
        value: "http://localhost:3000,https://campusdeal.vercel.app,https://campusdealls.netlify.app,https://bespoke-meringue-7b37b6.netlify.app"
      - key: DATABASE_URL
        fromDatabase:
          name: campusdeal-db
          property: connectionString
      - key: PAYSTACK_PUBLIC_KEY
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: SENDCHAMP_PUBLIC_KEY
        sync: false
      - key: SENDCHAMP_SECRET_KEY
        sync: false
      - key: SENDCHAMP_SENDER_ID
        value: "Sendchamp"
      - key: SENDCHAMP_BASE_URL
        value: "https://api.sendchamp.com/api/v1"
      - key: CLOUDINARY_CLOUD_NAME
        value: "campusdeal"
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: SECURE_SSL_REDIRECT
        value: "False"
      - key: SESSION_COOKIE_SECURE
        value: "True"
      - key: CSRF_COOKIE_SECURE
        value: "True"

databases:
  - name: campusdeal-db
    databaseName: campusdeal
    user: campusdeal
    plan: free
    region: frankfurt
