services:
  - type: web
    name: campusdeal-backend
    env: python
    plan: free
    region: fremont
    branch: main
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn campusdeal.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        fromService: secret
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "campusdeal-backend.onrender.com"
      - key: FRONTEND_URL
        value: "https://your-frontend-host.com"
      - key: DATABASE_URL
        fromService: campusdeal-db
      - key: PAYSTACK_PUBLIC_KEY
        fromService: secret
      - key: PAYSTACK_SECRET_KEY
        fromService: secret
      - key: SENDCHAMP_PUBLIC_KEY
        fromService: secret
      - key: SENDCHAMP_SECRET_KEY
        fromService: secret
      - key: SENDCHAMP_SENDER_ID
        value: "Sendchamp"
      - key: SENDCHAMP_BASE_URL
        value: "https://api.sendchamp.com/api/v1"
      - key: CLOUDINARY_CLOUD_NAME
        fromService: secret
      - key: CLOUDINARY_API_KEY
        fromService: secret
      - key: CLOUDINARY_API_SECRET
        fromService: secret
      - key: CORS_ALLOWED_ORIGINS
        value: "https://your-frontend-host.com"

databases:
  - name: campusdeal-db
    engine: postgresql
    plan: free
    region: fremont
    version: 15
