# Generated by Django 4.2.17 on 2026-02-09 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlisting',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/'),
        ),
    ]
