# Generated by Django 4.2.17 on 2026-02-21 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0002_alter_itemlisting_image_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('not_as_described', 'Item Not as Described'), ('damaged', 'Damaged on Delivery'), ('wrong_item', 'Wrong Item Received'), ('seller_unresponsive', 'Seller Unresponsive'), ('other', 'Other')], max_length=30)),
                ('detailed_explanation', models.TextField()),
                ('evidence_image_1', models.ImageField(blank=True, null=True, upload_to='refund_evidence/')),
                ('evidence_image_2', models.ImageField(blank=True, null=True, upload_to='refund_evidence/')),
                ('evidence_image_3', models.ImageField(blank=True, null=True, upload_to='refund_evidence/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processed', 'Refund Processed')], default='pending', max_length=15)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund_request', to='marketplace.order')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', '-created_at'], name='marketplace_status_fdf755_idx')],
            },
        ),
    ]
