# Generated by Django 4.2.17 on 2026-02-25 15:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0003_refundrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('location', models.CharField(choices=[('ilorin', 'Ilorin'), ('malete', 'Malete'), ('offa', 'Offa')], max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('rent_per_month', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('amenities', models.JSONField(default=list)),
                ('contact_phone', models.CharField(max_length=20)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='hostel_images/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='hostel_images/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='hostel_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_notes', models.TextField(blank=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_verified', 'is_active', 'location', '-created_at'], name='marketplace_is_veri_2cb860_idx'), models.Index(fields=['landlord', '-created_at'], name='marketplace_landlor_a12862_idx')],
            },
        ),
    ]
