# Generated by Django 4.2.17 on 2026-03-13 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0005_withdrawal'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformFinancials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_funds_liability', models.DecimalField(decimal_places=2, default=0, help_text='Total amount owed to sellers in escrow/wallets', max_digits=12)),
                ('platform_revenue', models.DecimalField(decimal_places=2, default=0, help_text='Platform profit from fees', max_digits=12)),
                ('paystack_balance', models.DecimalField(decimal_places=2, default=0, help_text='Actual balance in Paystack account', max_digits=12)),
                ('last_reconciliation', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Financials',
                'verbose_name_plural': 'Platform Financials',
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('payment_received', 'Payment Received'), ('withdrawal_processed', 'Withdrawal Processed'), ('service_fee_earned', 'Service Fee Earned'), ('withdrawal_fee_earned', 'Withdrawal Fee Earned'), ('refund_issued', 'Refund Issued'), ('platform_withdrawal', 'Platform Withdrawal'), ('reconciliation', 'Reconciliation Adjustment')], max_length=30)),
                ('user_liability_change', models.DecimalField(decimal_places=2, default=0, help_text='Change in what we owe users (+ increase, - decrease)', max_digits=10)),
                ('platform_revenue_change', models.DecimalField(decimal_places=2, default=0, help_text='Change in platform profit (+ increase, - decrease)', max_digits=10)),
                ('paystack_balance_change', models.DecimalField(decimal_places=2, default=0, help_text='Change in Paystack balance (+ increase, - decrease)', max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_liability_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('platform_revenue_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paystack_balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.order')),
                ('related_withdrawal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.withdrawal')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='marketplace_created_1c4c69_idx'), models.Index(fields=['transaction_type'], name='marketplace_transac_85c1b6_idx')],
            },
        ),
    ]
