# Generated by Django 5.1.6 on 2026-06-03 02:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_platformfinancials_financialtransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostellisting',
            name='location',
            field=models.CharField(choices=[('ilorin', 'Ilorin'), ('malete', 'Malete'), ('offa', 'Offa'), ('lagos', 'Lagos'), ('abuja', 'Abuja'), ('ibadan', 'Ibadan'), ('kano', 'Kano'), ('port-harcourt', 'Port Harcourt')], max_length=20),
        ),
        migrations.AlterField(
            model_name='itemlisting',
            name='location',
            field=models.CharField(choices=[('ilorin', 'Ilorin'), ('malete', 'Malete'), ('offa', 'Offa'), ('lagos', 'Lagos'), ('abuja', 'Abuja'), ('ibadan', 'Ibadan'), ('kano', 'Kano'), ('port-harcourt', 'Port Harcourt')], max_length=20),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('message', models.TextField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('delivery_method', models.CharField(choices=[('campusdeal', 'CampusDeal'), ('seller', 'Seller'), ('pickup', 'Pickup')], default='pickup', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_made', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='marketplace.itemlisting')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer', to='marketplace.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['item', 'status'], name='marketplace_item_id_3551c6_idx'), models.Index(fields=['buyer', '-created_at'], name='marketplace_buyer_i_a4ac9f_idx')],
            },
        ),
    ]
