# Generated by Django 5.1.6 on 2026-06-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_alter_hostellisting_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payout_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='paystack_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='transfer_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
